name: Build-Test-Deploy
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build-test-unit:
    runs-on: ubuntu-latest
    steps:
    - name: Repo checkout
      uses: actions/checkout@v4
    - name: Use Node.js latest 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install npm dependencies
      run: npm i
    - name: Run unit tests
      run: npm run test:unit
    - name: Display SoftUni username
      run: echo "mr.d.dimitrov"

  run-ui-tests:
    needs: build-test-unit
    runs-on: ubuntu-latest
    steps:
    - name: Repo checkout
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install NPM dependencies
      run: npm i
    - name: Install Playwright
      run: npx playwright install
    - name: Run app in background
      run: npm run start &
    - name: Run UI tests
      run: npm run test:ui

  deploy:
    needs: run-ui-tests
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: JorgeLNJunior/render-deploy@v1.4.4
          with:
            service_id: ${{ secrets.MY_RENDER_SERVICE_ID }}
            api_key: ${{ secrets.RENDER_API_KEY }}
            wait_deploy: true 